-- 07_populate_dummy_data.sql

-- ==========================================
-- 1. Inserir Profissionais Fictícios
-- ==========================================

-- Profissional 1: Cuidador de Idosos (Florianópolis) - Econômico
INSERT INTO public.profissionais_cadastros (
  id, 
  nome_completo, 
  whatsapp, 
  status, 
  categoria_profissional, 
  cidade, 
  bairro, 
  endereco_base_completo, 
  endereco_base_numero, 
  latitude_base, 
  longitude_base, 
  raio_atendimento_km, 
  valor_minimo_12h, 
  valor_minimo_24h, 
  localizacao_pendente,
  tipos_atendimento,
  tempo_experiencia,
  disponibilidade,
  regioes_atende,
  privacy_accepted_at,
  contact_accepted_at,
  veracity_accepted_at
) VALUES (
  gen_random_uuid(), 
  'Maria Oliveira (Fictício)', 
  '48999991111', 
  'Validado', 
  'Cuidador de Idosos', 
  'Florianópolis', 
  'Centro', 
  'Rua Felipe Schmidt', 
  '100', 
  -27.595, 
  -48.548, 
  15, 
  120.00, 
  220.00, 
  false,
  'Idosos Acamados, Parkinson, Alzheimer',
  'Mais de 5 anos',
  'Integral',
  'Florianópolis e São José',
  now(),
  now(),
  now()
);

-- Profissional 2: Técnico de Enfermagem (São José) - Mais experiente/Caro
INSERT INTO public.profissionais_cadastros (
  id, 
  nome_completo, 
  whatsapp, 
  status, 
  categoria_profissional, 
  cidade, 
  bairro, 
  endereco_base_completo, 
  endereco_base_numero, 
  latitude_base, 
  longitude_base, 
  raio_atendimento_km, 
  valor_minimo_12h, 
  valor_minimo_24h, 
  localizacao_pendente,
  tipos_atendimento,
  tempo_experiencia,
  disponibilidade,
  regioes_atende,
  privacy_accepted_at,
  contact_accepted_at,
  veracity_accepted_at
) VALUES (
  gen_random_uuid(), 
  'João Santos (Fictício)', 
  '48999992222', 
  'Validado', 
  'Técnico de Enfermagem', 
  'São José', 
  'Kobrasol', 
  'Avenida Lédio João Martins', 
  '500', 
  -27.593, 
  -48.611, 
  20, 
  180.00, 
  350.00, 
  false,
  'Curativos, Pós-operatório, Medicação Injetável',
  '10 anos',
  'Noturno e Finais de Semana',
  'Grande Florianópolis',
  now(),
  now(),
  now()
);

-- Profissional 3: Cuidador de Idosos (Palhoça) - Médio
INSERT INTO public.profissionais_cadastros (
  id, 
  nome_completo, 
  whatsapp, 
  status, 
  categoria_profissional, 
  cidade, 
  bairro, 
  endereco_base_completo, 
  endereco_base_numero, 
  latitude_base, 
  longitude_base, 
  raio_atendimento_km, 
  valor_minimo_12h, 
  valor_minimo_24h, 
  localizacao_pendente,
  tipos_atendimento,
  tempo_experiencia,
  disponibilidade,
  regioes_atende,
  privacy_accepted_at,
  contact_accepted_at,
  veracity_accepted_at
) VALUES (
  gen_random_uuid(), 
  'Ana Costa (Fictício)', 
  '48999993333', 
  'Validado', 
  'Cuidador de Idosos', 
  'Palhoça', 
  'Pagani', 
  'Avenida Atílio Pedro Pagani', 
  '300', 
  -27.645, 
  -48.667, 
  15, 
  140.00, 
  250.00, 
  false,
  'Cuidados básicos, Companhia, Banhos',
  '2 anos',
  'Diurno',
  'Palhoça e São José',
  now(),
  now(),
  now()
);

-- ==========================================
-- 2. Inserir Solicitações da Família
-- ==========================================

-- Solicitação 1: Urgente e Econômica no Centro de Floripa
INSERT INTO public.familias_solicitacoes (
  nome_completo, 
  whatsapp, 
  endereco_cep, 
  endereco_completo, 
  endereco_numero, 
  bairro,
  endereco_bairro, 
  cidade,
  endereco_cidade, 
  endereco_estado, 
  latitude, 
  longitude, 
  para_quem, 
  tipo_profissional, 
  data_desejada, 
  horario_desejado, 
  horario_fim, 
  duracao_plantao, 
  preferencia_atendimento, 
  e_urgente, 
  status,
  codigo_acompanhamento,
  privacy_accepted_at,
  contact_accepted_at
) VALUES (
  'Carlos Silva (Família Fictícia)', 
  '48999994444', 
  '88015-200', 
  'Avenida Hercílio Luz', 
  '1200', 
  'Centro', 
  'Centro', 
  'Florianópolis', 
  'Florianópolis', 
  'SC', 
  -27.598, 
  -48.545, 
  'Pai, 85 anos', 
  'Cuidador de Idosos', 
  '2026-06-20', 
  '08:00', 
  '20:00', 
  'Apenas 1 dia', 
  'Opção mais econômica', 
  true, 
  'Novo pedido',
  'FAM-001',
  now(),
  now()
);

-- Solicitação 2: Técnico de Enfermagem em São José
INSERT INTO public.familias_solicitacoes (
  nome_completo, 
  whatsapp, 
  endereco_cep, 
  endereco_completo, 
  endereco_numero, 
  bairro,
  endereco_bairro, 
  cidade,
  endereco_cidade, 
  endereco_estado, 
  latitude, 
  longitude, 
  para_quem, 
  tipo_profissional, 
  data_desejada, 
  horario_desejado, 
  horario_fim, 
  duracao_plantao, 
  preferencia_atendimento, 
  e_urgente, 
  status,
  codigo_acompanhamento,
  privacy_accepted_at,
  contact_accepted_at
) VALUES (
  'Fernanda Souza (Família Fictícia)', 
  '48999995555', 
  '88101-000', 
  'Rua Koesa', 
  '150', 
  'Kobrasol', 
  'Kobrasol', 
  'São José', 
  'São José', 
  'SC', 
  -27.591, 
  -48.608, 
  'Mãe, pós-operatório', 
  'Técnico de Enfermagem', 
  '2026-06-22', 
  '19:00', 
  '07:00', 
  '3 noites', 
  'Priorizar profissional mais experiente', 
  false, 
  'Em análise',
  'FAM-002',
  now(),
  now()
);

-- Solicitação 3: Cuidador em Palhoça
INSERT INTO public.familias_solicitacoes (
  nome_completo, 
  whatsapp, 
  endereco_cep, 
  endereco_completo, 
  endereco_numero, 
  bairro,
  endereco_bairro, 
  cidade,
  endereco_cidade, 
  endereco_estado, 
  latitude, 
  longitude, 
  para_quem, 
  tipo_profissional, 
  data_desejada, 
  horario_desejado, 
  horario_fim, 
  duracao_plantao, 
  preferencia_atendimento, 
  e_urgente, 
  status,
  codigo_acompanhamento,
  privacy_accepted_at,
  contact_accepted_at
) VALUES (
  'Rodrigo Lima (Família Fictícia)', 
  '48999996666', 
  '88132-149', 
  'Rua Najla Carone Goedert', 
  '800', 
  'Pagani', 
  'Pagani', 
  'Palhoça', 
  'Palhoça', 
  'SC', 
  -27.642, 
  -48.665, 
  'Avô, cadeirante', 
  'Cuidador de Idosos', 
  '2026-06-25', 
  '08:00', 
  '20:00', 
  'Segunda a Sexta', 
  'Quero receber estimativa antes de confirmar', 
  false, 
  'Procurando profissional',
  'FAM-003',
  now(),
  now()
);
